services:
  filebrowser:
    # ...
    labels:
      # --- Router (Intercettazione) ---
      traefik.http.routers.filebrowser_cfproxy.rule: Host(`cloud.filonzi.it`)
      traefik.http.routers.filebrowser_cfproxy.entrypoints: cfproxy
      
      # --- Il collegamento al Service ---
      traefik.http.routers.filebrowser_cfproxy.service: filebrowser_cfproxy

      # --- Servizio (Destinazione) ---
      traefik.http.services.filebrowser_cfproxy.loadbalancer.server.port: 80

      # --- Generale ---
      traefik.enable: "true"
      traefik.docker.network: "cust_traefik"
      
    networks:
      - cust_traefik

networks:
  cust_traefik:
    external: true
