services:
  ntfy:
    # ...
    labels:
      # --- Router (Intercettazione) ---
      traefik.http.routers.ntfy_cfproxy.rule: Host(`${DOMAIN}`)
      traefik.http.routers.ntfy_cfproxy.entrypoints: cfproxy
      
      # --- Il collegamento al Service ---
      traefik.http.routers.ntfy_cfproxy.service: ntfy_cfproxy

      # --- Servizio (Destinazione) ---
      traefik.http.services.ntfy_cfproxy.loadbalancer.server.port: 80

      # --- Generale ---
      traefik.enable: true
      traefik.docker.network: "cust_traefik"
      
    networks:
      - cust_traefik

networks:
  cust_traefik:
    external: true
