services:
  n8n:
    # ...
    labels:
      # --- Router (Intercettazione) ---
      traefik.http.routers.n8n_cfproxy.rule: Host(`${DOMAIN}`)
      traefik.http.routers.n8n_cfproxy.entrypoints: cfproxy
      
      # --- Il collegamento al Service ---
      traefik.http.routers.n8n_cfproxy.service: n8n_cfproxy

      # --- Servizio (Destinazione) ---
      traefik.http.services.n8n_cfproxy.loadbalancer.server.port: 5678

      # --- Generale ---
      traefik.enable: "true"
      traefik.docker.network: "cust_traefik"
      
    networks:
      - cust_traefik

networks:
  cust_traefik:
    external: true
