name: n8n
services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    stdin_open: true
    tty: true
    ports:
      - 8089:5678
    environment:
      - GENERIC_TIMEZONE=Europe/Rome
      - TZ=Europe/Rome
      - WEBHOOK_URL=https://${DOMAIN}/
      - N8N_PROXY_HOPS=1
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
    volumes:
      - ./data:/home/node/.n8n