# Useless bindings

unbind = SUPER, C
unbind = SUPER, V
unbind = SUPER, X
unbind = SUPER CTRL, V

unbind = SUPER,       G
unbind = SUPER ALT,   G

unbind = SUPER,       S
unbind = SUPER ALT,   S

###########################################################################



# Resize active window
unbind = SUPER ALT, left
unbind = SUPER ALT, right
unbind = SUPER ALT, up
unbind = SUPER ALT, down

bindd = SUPER ALT, left, Expand window left, resizeactive, -50 0
bindd = SUPER ALT, right, Shrink window left, resizeactive, 50 0
bindd = SUPER ALT, up, Shrink window up, resizeactive, 0 -50
bindd = SUPER ALT, down, Expand window down, resizeactive, 0 50


# FullScreen active window
unbind = SUPER, F
unbind = SUPER CTRL, F
unbind = SUPER ALT, F

bindd = SUPER, F, Full width, fullscreen, 1
bindd = SUPER ALT, F, Full screen, fullscreen, 0


###########################################################################
# System
bindd = CTRL, SPACE, Toggle floating and center, resizeactive, exact 1800 950
bindd = CTRL, SPACE, CenterWindow, centerwindow

bindd = SUPER, L, Lock system, exec, omarchy-lock-screen

###########################################################################

bindd = SUPER,          E,      File manager,       exec, uwsm-app -- nautilus --new-window
bindd = SUPER SHIFT,    E,      FileBrowser,        exec, omarchy-launch-webapp "https://cloud.filonzi.it"



unbind = SUPER,         B
unbind = SUPER ALT,     B
unbind = SUPER SHIFT,   B
bindd = SUPER,          B,      Browser,            exec, $browser
bindd = SUPER ALT,      B,      Browser (private),  exec, $browser --private



unbind = SUPER,         A
unbind = SUPER ALT,     A
unbind = SUPER SHIFT,   A
unbind = SUPER CTRL,    A

bindd = SUPER,          A,      Gemini,             exec, omarchy-launch-webapp "https://gemini.google.com"
bindd = SUPER SHIFT,    A,      ChatGPT,            exec, omarchy-launch-webapp "https://chatgpt.com"
bindd = SUPER ALT,      A,      Perplexity,         exec, omarchy-launch-webapp "https://perplexity.ai"
bindd = SUPER CTRL,     A,      Claude,             exec, omarchy-launch-webapp "https://claude.ai"



unbind = SUPER,         M
unbind = SUPER ALT,     M
unbind = SUPER CTRL,    M
unbind = SUPER SHIFT,   M

bindd = SUPER,          M,      WhatsApp,           exec, omarchy-launch-or-focus-webapp WhatsApp "https://web.whatsapp.com/"
bindd = SUPER ALT,      M,      Google Messages,    exec, omarchy-launch-or-focus-webapp "Google Messages" "https://messages.google.com/web/conversations"
bindd = SUPER SHIFT,    M,      Telegram Desktop,   exec, Telegram


bindd = SUPER SHIFT,    G,      GitHub,             exec, omarchy-launch-webapp "https://github.com/jacopofilonzi"
bindd = SUPER,          G,      GMail,              exec, omarchy-launch-webapp "https://mail.google.com"

unbind = SUPER SHIFT,   P

bindd = SUPER SHIFT,    P,      1Password,          exec, 1password


bindd = SUPER SHIFT,    S,      LocalSend - Share,  exec, localsend
