$WAPP = web\.whatsapp\.com
$WAPP = $WAPP|messages\.google\.com
$WAPP = $WAPP|calendar\.google\.com


# Costruisce la regex finale:
$WAPP = ^(chrome-($WAPP)__.*-Default)$


#---------------------------------------------------
$APP = org.kde.kdeconnect.(app|sms)
$APP = $APP|org.telegram.desktop
$APP = $APP|1password
$APP = $APP|it.filonzi.bluetui


windowrulev2 = float, class:^($WAPP|$APP)
windowrulev2 = size 1200 700, class:^($WAPP|$APP)

#---------------------------------------------------
# Bigger floating apps
#
#$BAPP = ""
#$BWAPP = mail\.google\.com
#$BWAPP = ^(chrome-($BWAPP)__.*-Default)$
#
#
#windowrulev2 = float, class: ^($BAPP|$BWAPP)
#windowrulev2 = size 1800 950, class:^($BAPP|$BWAPP)

