source = ~/dotfiles/.config/omarchy/hypr/bindings.conf
source = ~/dotfiles/.config/omarchy/hypr/floating_apps.conf
source = ~/dotfiles/.config/omarchy/hypr/auto-start.conf


gesture = 3, horizontal, workspace
