source = ~/dotfiles/.config/omarchy/hypr/bindings.conf
source = ~/dotfiles/.config/omarchy/hypr/floating_apps.conf
source = ~/dotfiles/.config/omarchy/hypr/auto-start.conf


gesture = 3, horizontal, workspace

# Swipe 4 dita a SINISTRA -> Sposta la finestra al workspace SUCCESSIVO (+1)
gesture = 4, left, dispatcher, movetoworkspace, -1

# Swipe 4 dita a DESTRA -> Sposta la finestra al workspace PRECEDENTE (-1)
gesture = 4, right, dispatcher, movetoworkspace, +1
